# Generated by Django 3.0.7 on 2020-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
