# Generated by Django 3.0.7 on 2020-06-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_auto_20200622_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
