# Generated by Django 3.0.7 on 2020-07-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_auto_20200630_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hours',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
