# Generated by Django 3.0.7 on 2020-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_auto_20200630_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='length',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
