# Generated by Django 3.0.7 on 2020-07-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_auto_20200701_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hours',
        ),
    ]
