# Generated by Django 3.0.7 on 2020-06-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0006_auto_20200623_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time_in', 'time_out']},
        ),
    ]
