# Generated by Django 3.0.7 on 2020-09-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0009_schedule_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
