# Generated by Django 3.0.7 on 2020-06-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0011_auto_20200624_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
