# Generated by Django 3.0.7 on 2020-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0004_auto_20200622_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['time_in']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hours',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
